# Generated by Django 4.2.7 on 2023-12-03 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='majors',
            new_name='major',
        ),
    ]
